/**
 * The masking executor. The safety interlock, the batched-UPDATE generation (including composite
 * primary keys), and the resumable per-rule progress are pure and unit tested; `runMasking` is the
 * thin impure loop that reads batches, applies `maskValue`, and writes them back.
 *
 * Masking is irreversible, and a run that dies partway leaves the branch PARTIALLY masked — which
 * looks masked but is not — so progress is written to runs.detail after every batch to make a run
 * resumable rather than a guess.
 */

import { quoteIdent, type Queryable } from "@neon-blocks/core";
import { maskValue } from "./mask.js";

export interface Rule {
  id: string;
  target_schema: string;
  target_table: string;
  target_column: string;
  strategy: string;
}

/** The interlock: refuse to mask unless the branch name matches the allow pattern. */
export function isBranchAllowed(branchName: string | null | undefined, patternSource: string): boolean {
  if (!branchName) return false;
  return new RegExp(patternSource).test(branchName);
}

/** Stable key for a rule inside runs.detail. */
export function ruleKey(rule: Pick<Rule, "target_schema" | "target_table" | "target_column">): string {
  return `${rule.target_schema}.${rule.target_table}.${rule.target_column}`;
}

/** SELECT one batch of (key columns, value), ordered and cursored by the primary key. */
export function buildSelectBatchSql(
  rule: Rule,
  keyColumns: readonly string[],
  withCursor: boolean,
): string {
  if (keyColumns.length === 0) throw new Error("a masking target needs at least one key column");
  const table = `${quoteIdent(rule.target_schema)}.${quoteIdent(rule.target_table)}`;
  const col = quoteIdent(rule.target_column);
  const keys = keyColumns.map((k) => quoteIdent(k));
  const keyList = keys.join(", ");
  // Composite tuple comparison gives a correct, index-friendly cursor for multi-column keys.
  const cursor = withCursor
    ? ` AND (${keyList}) > (${keyColumns.map((_, i) => `$${i + 1}`).join(", ")})`
    : "";
  const limit = withCursor ? `$${keyColumns.length + 1}` : "$1";
  return `SELECT ${keyList}, ${col} AS _value
          FROM ${table}
          WHERE ${col} IS NOT NULL${cursor}
          ORDER BY ${keyList}
          LIMIT ${limit}`;
}

/**
 * Batched UPDATE that sets the target column from a VALUES list keyed by the primary key. Keys are
 * compared as text so the statement works for any key type; placeholders are row-major
 * `[...keyValues, maskedValue]`.
 */
export function buildUpdateSql(rule: Rule, keyColumns: readonly string[], rowCount: number): string {
  if (keyColumns.length === 0) throw new Error("a masking target needs at least one key column");
  if (rowCount < 1) throw new Error("no rows to update");
  const table = `${quoteIdent(rule.target_schema)}.${quoteIdent(rule.target_table)}`;
  const col = quoteIdent(rule.target_column);
  const perRow = keyColumns.length + 1;

  const tuples: string[] = [];
  let p = 1;
  for (let r = 0; r < rowCount; r++) {
    tuples.push(`(${Array.from({ length: perRow }, () => `$${p++}`).join(", ")})`);
  }
  const dataCols = [...keyColumns.map((_, i) => `k${i}`), "new_value"];
  const where = keyColumns.map((k, i) => `tgt.${quoteIdent(k)}::text = data.k${i}`).join(" AND ");

  return `UPDATE ${table} AS tgt
          SET ${col} = data.new_value
          FROM (VALUES ${tuples.join(", ")}) AS data(${dataCols.join(", ")})
          WHERE ${where}`;
}

export interface RuleProgress {
  rowsMasked: number;
  done: boolean;
  cursor: (string | number)[] | null;
}

/** Merge a batch's progress into runs.detail, accumulating rows so a resumed run stays accurate. */
export function mergeProgress(
  detail: Record<string, unknown>,
  key: string,
  add: { rowsMasked: number; done: boolean; cursor: (string | number)[] | null },
): Record<string, unknown> {
  const prev = (detail[key] as RuleProgress | undefined) ?? { rowsMasked: 0, done: false, cursor: null };
  return {
    ...detail,
    [key]: {
      rowsMasked: prev.rowsMasked + add.rowsMasked,
      done: add.done,
      cursor: add.cursor ?? prev.cursor ?? null,
    },
  };
}

/** Primary-key columns for a table, from the catalog. */
export async function getPrimaryKeyColumns(
  db: Queryable,
  schema: string,
  table: string,
): Promise<string[]> {
  const { rows } = await db.query<{ attname: string }>(
    `SELECT a.attname
     FROM pg_index i
     JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
     WHERE i.indrelid = to_regclass($1) AND i.indisprimary
     ORDER BY array_position(i.indkey, a.attnum)`,
    [`${schema}.${table}`],
  );
  return rows.map((r) => r.attname);
}

/**
 * Apply every active rule to the branch in batches, updating runs.detail and the run totals as it
 * goes. Impure and cannot run offline; the SQL it issues is generated by the pure builders above.
 */
export async function runMasking(
  db: Queryable,
  opts: { runId: string; rules: readonly Rule[]; salt: string; batchRows: number },
): Promise<{ rulesApplied: number; rowsMasked: number }> {
  let detail: Record<string, unknown> = {};
  let totalRows = 0;
  let rulesApplied = 0;

  for (const rule of opts.rules) {
    const keyColumns = await getPrimaryKeyColumns(db, rule.target_schema, rule.target_table);
    if (keyColumns.length === 0) {
      detail = mergeProgress(detail, ruleKey(rule), { rowsMasked: 0, done: false, cursor: null });
      continue; // cannot batch a table with no primary key
    }

    let cursor: (string | number)[] | null = null;
    for (;;) {
      const params: unknown[] = cursor !== null ? [...cursor, opts.batchRows] : [opts.batchRows];
      const { rows } = await db.query<Record<string, unknown>>(
        buildSelectBatchSql(rule, keyColumns, cursor !== null),
        params,
      );
      if (rows.length === 0) break;

      const updateValues: unknown[] = [];
      for (const row of rows) {
        const keyValues = keyColumns.map((k) => row[k] as string | number);
        const masked = maskValue(String(row["_value"] ?? ""), opts.salt, rule.strategy);
        updateValues.push(...keyValues.map((v) => String(v)), masked);
      }
      await db.query(buildUpdateSql(rule, keyColumns, rows.length), updateValues);

      const last = rows[rows.length - 1] as Record<string, unknown>;
      cursor = keyColumns.map((k) => last[k] as string | number);
      totalRows += rows.length;
      const done = rows.length < opts.batchRows;
      detail = mergeProgress(detail, ruleKey(rule), { rowsMasked: rows.length, done, cursor });
      await db.query(
        `UPDATE blocks_pii_anonymizer.runs SET rows_masked = $2, detail = $3::jsonb WHERE id = $1`,
        [opts.runId, totalRows, JSON.stringify(detail)],
      );
      if (done) break;
    }
    rulesApplied++;
  }

  return { rulesApplied, rowsMasked: totalRows };
}
