#!/usr/bin/env node
/**
 * Build release artifacts for the console catalog.
 *
 * Each block becomes a self-contained tarball the Neon function deploy API can fetch and deploy
 * without the monorepo present. A catalog.json index sits alongside them, which is what the console
 * reads to populate its browse UI — DockerHub-shaped: name, summary, README, version, config schema.
 *
 * The key property is that **artifacts are public and inert**. A tarball contains bundled code,
 * migrations, and a manifest — no credentials of any kind. `DATABASE_URL`, storage, and AI Gateway
 * credentials are injected by Neon into the deployed function, and the per-install trigger secret is
 * generated by the console at install time. So these can be served from anywhere, unauthenticated,
 * which is what makes the whole model simple.
 *
 *   node scripts/build-release.mjs [--version 0.1.0] [--out dist-release]
 */

import { mkdir, readFile, writeFile, rm } from "node:fs/promises";
import { createHash } from "node:crypto";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import path from "node:path";
import { fileURLToPath } from "node:url";

const run = promisify(execFile);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const args = process.argv.slice(2);
const argOf = (flag, fallback) => {
  const i = args.indexOf(flag);
  return i >= 0 && args[i + 1] ? args[i + 1] : fallback;
};

const rootPkg = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"));
const version = argOf("--version", rootPkg.version);
const outDir = path.resolve(root, argOf("--out", "dist-release"));

if (!/^\d+\.\d+\.\d+(-[\w.]+)?$/.test(version)) {
  console.error(`Version "${version}" is not semver. The console relies on it for upgrade ordering.`);
  process.exit(1);
}

const { discoverBlocks } = await import(path.join(root, "packages/cli/dist/index.js"));
const { loadMigrations } = await import(path.join(root, "packages/migrate/dist/index.js"));

await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

const blocks = await discoverBlocks(path.join(root, "blocks"));
console.log(`Building ${blocks.length} blocks at version ${version}\n`);

const catalog = [];
let failures = 0;

for (const { manifest, dir } of blocks) {
  const stage = path.join(outDir, ".stage", manifest.slug);
  await mkdir(path.join(stage, "migrations"), { recursive: true });

  try {
    // Bundle to a single file. The workspace @neon-blocks/* imports inline away entirely, which is
    // what makes the artifact standalone — without this the deploy API would need the monorepo.
    //
    // `pg` stays external: it is a native-ish driver the runtime provides, and bundling it would
    // both bloat the artifact and risk the native-binary problem that breaks the default esbuild
    // path (see docs/RUNTIME.md).
    const entry = path.join(dir, "src/index.ts");
    const bundlePath = path.join(stage, "index.js");

    await run("npx", [
      "esbuild",
      entry,
      "--bundle",
      "--platform=node",
      "--format=esm",
      "--target=node24",
      "--external:pg",
      // Keep names readable: a stack trace from a user's deployed function is the only debugging
      // signal available, and minified frames make it useless.
      "--keep-names",
      `--outfile=${bundlePath}`,
    ], { cwd: root });

    const bundle = await readFile(bundlePath, "utf8");

    // A bundle that still references a workspace path did not inline correctly and would fail at
    // invoke with a module-not-found, which is a confusing way to learn about a build problem.
    if (/@neon-blocks\//.test(bundle)) {
      throw new Error("bundle still references @neon-blocks/* — it is not self-contained");
    }

    const migrations = await loadMigrations(path.join(dir, "migrations"));
    for (const migration of migrations) {
      const base = `${migration.version}_${migration.name}`;
      await writeFile(path.join(stage, "migrations", `${base}.sql`), migration.upSql);
      if (migration.downSql) {
        await writeFile(path.join(stage, "migrations", `${base}.down.sql`), migration.downSql);
      }
    }

    // README travels with the artifact so the console can render docs without a second fetch, and so
    // the artifact remains self-describing if it is ever mirrored.
    const readme = await readFile(path.join(dir, "README.md"), "utf8").catch(() => "");
    if (readme) await writeFile(path.join(stage, "README.md"), readme);

    // The deployed manifest carries the version; the source manifest deliberately does not, so a
    // release is the only thing that stamps one.
    const deployed = { ...manifest, version, bundledAt: null };
    await writeFile(path.join(stage, "block.json"), `${JSON.stringify(deployed, null, 2)}\n`);

    const tarball = `neon-blocks-${manifest.slug}-${version}.tar.gz`;
    await run("tar", ["-czf", path.join(outDir, tarball), "-C", stage, "."]);

    const bytes = await readFile(path.join(outDir, tarball));
    // Integrity digest so the console can verify what it fetched. Not a signature — that needs a
    // key and a threat model, and is noted as a gap rather than faked.
    const digest = createHash("sha256").update(bytes).digest("hex");

    catalog.push({
      slug: manifest.slug,
      version,
      name: manifest.name,
      summary: manifest.summary,
      // Ordering hint for the console's default sort: foundations first.
      order: manifest.rank,
      schema: manifest.schema,
      depth: manifest.depth,
      capabilities: manifest.capabilities,
      dependsOn: manifest.dependsOn,
      // Everything the console needs to render an install form. `injected` marks variables Neon
      // supplies, which must NOT be prompted for.
      config: manifest.env.map((e) => ({
        name: e.name,
        description: e.description,
        required: e.required === true,
        default: e.default ?? null,
        injected: e.injected === true,
        secret: /SECRET|TOKEN|KEY|PASSWORD|CREDENTIAL/.test(e.name),
        example: e.example ?? null,
      })),
      triggers: manifest.triggers,
      migrationCount: migrations.length,
      readme: readme ? `${manifest.slug}/README.md` : null,
      artifact: { file: tarball, bytes: bytes.length, sha256: digest },
    });

    console.log(
      `  ${manifest.slug.padEnd(22)} ${String(Math.round(bundle.length / 1024)).padStart(4)}KB js  ` +
        `${String(migrations.length).padStart(2)} migration(s)  →  ${tarball}`,
    );
  } catch (err) {
    failures++;
    console.error(`  ${manifest.slug.padEnd(22)} FAILED: ${err instanceof Error ? err.message : err}`);
  }
}

await rm(path.join(outDir, ".stage"), { recursive: true, force: true });

if (failures > 0) {
  console.error(`\n${failures} block(s) failed to build.`);
  process.exit(1);
}

// The catalog index. This is the console's entry point: fetch it, render a browse UI, and use each
// entry's artifact URL for the deploy call.
const index = {
  catalogVersion: 1,
  release: version,
  // Generated at publish time by CI, which has a real clock. Left null here so the build is
  // reproducible — two builds of the same commit produce identical bytes.
  publishedAt: null,
  blockCount: catalog.length,
  blocks: catalog.sort((a, b) => a.order - b.order),
};

await writeFile(path.join(outDir, "catalog.json"), `${JSON.stringify(index, null, 2)}\n`);

const totalBytes = catalog.reduce((sum, b) => sum + b.artifact.bytes, 0);
console.log(
  `\ncatalog.json + ${catalog.length} tarballs in ${path.relative(root, outDir)}/ ` +
    `(${Math.round(totalBytes / 1024)}KB total)`,
);
console.log("Artifacts contain no credentials and can be served unauthenticated.");
